Avoid exception, if there are no changes
This happened in commit 486a3c24b6b92f1345c280f1e17e66c54e86cd92

```
TypeError: rec.changes is undefined                              w2ui.js (Zeile 3538)
...revious: (rec.changes.hasOwnProperty(col.field) ? rec.changes[col.field]: old_va...
```