w2grid: doSave() failed to trigger after-event when saving to a remote data source
inside the callback after completing the remote request, 'this' would point to the window object, thus this.trigger() would give a 'TypeError: this.trigger is not a function'.
I solved this by creating a reference to the 'real' this before the callback.